### ISSUE TITLE
Audit Maps

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/map_picker#11]
Get list of maps we need to make images for (CS:GO and Overwatch have both added maps since last LAN).

**Comment by TonyDiPietri** [comment]
Current CS:GO maplist: **de_inferno, de_nuke, de_cache, de_mirage, de_overpass, de_train, de_cobblestone**
New OW map is **Horizon Lunar Colony**.

**Comment by ChandlerTech** [comment]
Map List has been updated.
