### ISSUE TITLE
Fall 2019 - Rework logic for Overwatch Tournament

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/map_picker#18]
@TonyDiPietri has requirements in OneNote; please use this official github issues for any out-of-band communications.

**Comment by dudleycodes** [comment]
@TonyDiPietri will port notes from OneNote into this issue this evening (7/31/2019).

**Comment by TonyDiPietri** [comment]
Teams will flip a coin for first ban and then take turns banning and picking maps from the list in order until five maps have been chosen. One map will be chosen from each of the four categories and played in order: Control, Assault, Hybrid, and Escort. The final tiebreaker (5th) map will be a second Control map.

|Control | Assault | Hybrid | Escort |
|---------|--------|--------|--------|
Ilios | Hanamura | Hollywood | Havana
Busan | Volskaya | Blizzard | Junkertown
Lijiang | Anubis | King's   Row | Route   66

|-- |---- | 1st Map | 2nd Map |-- |-- | 3rd Map | 4th Map | 5th Map (2-2 Tie)  |
|---|----|----------|-----------|---|---|---------|----------|-----------|
|Team 1|BAN||PICK||BAN||PICK|||
|Team 2||BAN||PICK||BAN||PICK|PICK

**Comment by TonyDiPietri** [comment]
Business-style rules:

* Order is two bans, two picks, two bans, two picks
* Cannot ban more than 1 Control map
* Cannot ban more than 2 Assault maps
* Cannot ban more than 2 Hybrid maps
* Cannot ban more than 2 Escort maps
	
* Cannot pick more than 2 Control maps
* Cannot pick more than 1 Assault maps
* Cannot pick more than 1 Hybrid maps
* Cannot pick more than 1 Escort maps
	
* Maps must be played in order: Control, Assault, Hybrid, Escort, Control(Tiebreaker)

**Comment by ChandlerTech** [comment]
All changes for this ticket are being made in the map-picker repo under the "Overwatch-Rework" branch.

**Comment by natecowen** [comment]
@ChandlerTech  @TonyDiPietri  can you pull this branch and verify the logic. @ChandlerTech feel free to make changes. I know you wanted to make the output cleaner after we hit the checkbox.

**Comment by ChandlerTech** [comment]
@TonyDiPietri let us know what you think from a user standpoint when you operate the Overwatch game. You probably already know this, but we've made these changes on the "Overwatch-Rework" branch, so you'll want to update your local instance and git checkout this brach.
We can adjust the output more efficiently from your review. Thanks!
