### ISSUE TITLE
Audit CS:GO Images

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/map_picker#3]
Makes sure we have images for all CS:GO maps that can be used in the LL17 tournament.

Be mindful of the image requirements; refer to #1

Communicate with @ChandlerTech - make sure he knows the list of maps that will be in the LL17 tournament so that "map_picker.html" can be updated (if needed).

**Comment by TonyDiPietri** [comment]
Looked at all images for the seven maps we are using.
