### ISSUE TITLE
"overwatch_map_picker.html" is broken

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/map_picker#4]
- Showing some CS:GO maps
- Clicking on Overwatch images does nothing
- Formatting is off (Remember; we want to full-screen this on tablet)
- @TonyDiPietri will be cleaning up the Overwatch images themselves; see issue #1 for details.

![untitled](https://cloud.githubusercontent.com/assets/12804982/18891923/0bb463ca-84cd-11e6-9ebd-4f93dbb44b6f.png)

**Comment by dudleycodes** [comment]
Update as of 10/22/2016

All screens are broken

_overwatch_map_picker.html_ is in the same state as when this issue was opened
![over](https://cloud.githubusercontent.com/assets/12804982/19621727/b69f6886-985d-11e6-89e8-6aa073d52a8a.png)

_map_picker.html_ (CS:GO) is now broken
![go](https://cloud.githubusercontent.com/assets/12804982/19621731/d2b70574-985d-11e6-9c2f-c6d12140eb32.png)

**Comment by ChandlerTech** [comment]
Map_picker.html is no longer broken. Testable version has been committed to Master.
