### ISSUE TITLE
"selection_screen.html" is non-functional

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/map_picker#5]
If it was a placeholder let's nuke it from orbit.

If not it just needs to be flushed out; feel free to rename "map_picker.html" to "csgo_map_picker.html" (or whatever you'd prefer.

![untitled](https://cloud.githubusercontent.com/assets/12804982/18892071/b4c09920-84cd-11e6-8674-f77259ba059e.png)

**Comment by dudleycodes** [comment]
10/22/2016 Update

_selection_screen.html_ works but looks unprofessional
![sel](https://cloud.githubusercontent.com/assets/12804982/19621744/21647e72-985e-11e6-9a0a-95524a9afd9f.png)

No need for the Laclede's LAN logo or any text.  Please have it just CSGO / OVERWATCH with the logos side-by-side; each one taking up 50% of the screen.

Example:
![exa](https://cloud.githubusercontent.com/assets/12804982/19621755/56a3d196-985e-11e6-846f-2629b32f10c0.png)

**Comment by ChandlerTech** [comment]
Formatting has been corrected.
